[package]
authors = ["Scott Godwin <sgodwincs@gmail.com>"]
name = "rtsp"
version = "0.1.0"

[dependencies]
ascii = "0.8.6"
bytes = "0.4.5"
chrono = "0.4.0"
fnv = "1.0.5"
futures = "0.1.20"
lazy_static = "0.2.10"
regex = "0.2.2"
tokio-executor = "0.1.1"
tokio-io = "0.1.6"
tokio-tcp = "0.1.0"
tokio-timer = "0.2.3"
url = "1.6.0"

[dev-dependencies]
tokio = "0.1.6"
